<?php
  $random_title=array("Kata Ernest Prakasa Soal Luna Maya dan Via Vallen Rekam Adegan Film","Shandy Aulia Tampil Berhijab","Belum Resmi Tayang, Joko Anwar Rencanakan Sekuel Gundala","3 Top Moment Yayan Ruhian Syuting Bareng Keanu Reeves","Alasan Si Doel Tak Lagi Jadi Sinetron","Jisoo BLACKPINK Dikuntit, Privasi Diduga Tersebar di Grup Chat Porno","Menikah, Ridho DA dan Syifa Aisyah Undang Lesti Kejora?","4 Judul Film India Terbaik Versi Penggemar Bollywood","8 Pemotretan Artis Korea Kelewat Intim, Jang Ki Yong Buka-bukaan","Selena Gomez dan 6 Artis Barat Serahkan Keperawanan ke Seleb Lain");
  $random_topic=array("Blackpink","YG Entertainment","Nikita Mirzani","Deddy Corbuzier","Chow Yun Fat","Jackie Chan","Rachel Vennya","Drama Korea","Kim Kardashian","Angelina Jolie","Foto Bugil","Gosip","Squid Game","Pernikahan Siri");
  $random_kanal=array("Korea","Lokal","Barat","Asia","Korea","Lokal","Barat","Asia");
  $random_summary=array("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam erat orci, aliquam non nulla at, pretium feugiat lectus. Nulla rhoncus venenatis lacus ut facilisis.","Mauris semper condimentum nisl quis blandit. Curabitur tempus libero eu risus dapibus, id luctus tellus lacinia. Curabitur at molestie ex. Nulla hendrerit sem mauris, vel lobortis risus viverra et.","Pellentesque bibendum sem vitae diam euismod, semper congue justo posuere.","Aenean condimentum ex justo, eu sagittis nibh vulputate eget. Suspendisse potenti. Nam et urna vel urna efficitur malesuada non at nisi. Mauris vel leo sed diam ultrices pretium semper a turpis.");
  $random_author=array("Pay Joe","Marr Juo Kye","Jumy N'Ten","Shuu Trysh Noe","U Choqq","Bham Bank","Bank Toy Yiep","Pho Nie Mann","Rhou Jya Lee","Rush Die","Soul as Three","Pay Joe","Marr Juo Kye","Jumy N'Ten","Shuu Trysh Noe","U Choqq","Bham Bank","Bank Toy Yiep","Pho Nie Mann","Rhou Jya Lee","Rush Die","Soul as Three");
  $random_profession=array("Advokat","Agamawan","Akademisi","Aktivis","Atlet","Birokrat","Jurnalis","Pengusaha","Polisi","Politikus","Seniman","Tentara");
  $random_multibrand=array(
  '<a aria-label="JagoDangdut" class="title-network title-network-jagodangdut" href="https://www.thevivanetworks.com/prototype/seleb/" target="_blank"><h3>JagoDangdut</h3></a>',
  '<a aria-label="100KPJ" class="title-network title-network-100kpj" href="https://www.thevivanetworks.com/prototype/seleb/" target="_blank"><h3>100KPJ</h3></a>',
  '<a aria-label="IntipSeleb" class="title-network title-network-intipseleb" href="https://www.thevivanetworks.com/prototype/seleb/" target="_blank"><h3>IntipSeleb</h3></a>',
  '<a aria-label="Sahijab" class="title-network title-network-sahijab" href="https://www.thevivanetworks.com/prototype/seleb/" target="_blank"><h3>Sahijab</h3></a>',
  '<a aria-label="JagoDangdut" class="title-network title-network-jagodangdut" href="https://www.thevivanetworks.com/prototype/seleb/" target="_blank"><h3>JagoDangdut</h3></a>',
  '<a aria-label="100KPJ" class="title-network title-network-100kpj" href="https://www.thevivanetworks.com/prototype/seleb/" target="_blank"><h3>100KPJ</h3></a>',
  '<a aria-label="IntipSeleb" class="title-network title-network-intipseleb" href="https://www.thevivanetworks.com/prototype/seleb/" target="_blank"><h3>IntipSeleb</h3></a>',
  '<a aria-label="Sahijab" class="title-network title-network-sahijab" href="https://www.thevivanetworks.com/prototype/seleb/" target="_blank"><h3>Sahijab</h3></a>');
  $random_event=array("Hammersonic Festival 2021","Lauv - how im feeling world tour","Harry Styles - LOVE ON TOUR 2021","Louis Tomlinson World Tour 2021","Justin Bieber World Tour 2021","Foals Tour 2021","Martin Garrix World Tour 2021","Raisa LIVE IN CONCERT","ONE LIVE VIRTUAL CONCERT","BTS MAP OF THE SOUL ONE","Synchronize Festival 2020","Comika Day");
  $random_location=array("Dubai, AE","London, UK","Jakarta, ID","Seoul, KR","Los Angeles, US","Singapore, SG","Johannesburg, ZA","Sao Paulo, BR");
?>